baseURL = "https://nelsonmontalvo.com/"
languageCode = "en-us"
theme = "minimal"
title = "In Memorium Nelson Montalvo"

[params]
    subtitle = "1976-2008"
    author = "Montalvo Family"
    accent = "gray"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    homepagePic = "/images/nelson_bw.jpg"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://www.givedirect.org/give/givefrm.asp?CID=1013"
    name = "Donate to Humane Society"
    weight = 2

[[menu.main]]
    url = "/lastpicture"
    name = "Last Picture"
    weight = 3

[[menu.main]]
    url = "/blog"
    name = "Blog"
    weight = 4

[[menu.main]]
    url ="/obituary"
    name = "Obituary"
    weight = 5

[[menu.main]]
    url ="/funeral"
    name = "Funeral"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "fas fa-envelope"
#    weight = 1
#
#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "fab fa-github"
#    weight = 2
#
#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "fab fa-twitter"
#    weight = 3
#
#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "fab fa-linkedin"
#    weight = 4
#
#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "fab fa-stack-overflow"
#    weight = 5
